#!/bin/sh
#
#  pdns_auth_errors munin plugin.
#  Written by Florus Both <florus@yeetta.net> 2013-05-17
#  Placed in the public domain
#
#  Requires running as root:
#
#    echo '[pdns_auth_*]' >/etc/munin/plugin-conf.d/pdns_auth
#    echo 'user root' >>/etc/munin/plugin-conf.d/pdns_auth
#
#  Configuration variables:
#
#    pdns_control:    Path to rec_control executable
#                     (default: /usr/local/bin/pdns_control)

PDNS_CONTROL="${pdns_control:-/usr/local/bin/pdns_control}"

if [ "$1" = "autoconf" ]; then
	if [ -e "$PDNS_CONTROL" ]; then
		echo yes
		exit 0
	else
		echo no
		exit 1
	fi
fi

if [ "$1" = "config" ]; then
	echo 'graph_title PowerDNS Errors'
	echo 'graph_order cor servf timeo'
	echo 'graph_vlabel # of'
	echo 'graph_info PowerDNS health info'
	echo 'graph_category PowerDNS'

	echo 'cor.label Corrupt packets'
	echo 'cor.min 0'
	echo 'cor.type DERIVE'
	echo 'cor.info Corrupt packets'

	echo 'servf.label Servfail packets'
	echo 'servf.min 0'
	echo 'servf.type DERIVE'
	echo 'servf.info Servfail packets'

	echo 'timeo.label Timedout packets' 
	echo 'timeo.min 0'
	echo 'timeo.type DERIVE'
	echo 'timeo.info Timedout packets'

	exit 0
fi

echo cor.value `"$PDNS_CONTROL" show corrupt-packets`
echo servf.value `"$PDNS_CONTROL" show servfail-packets`
echo timeo.value `"$PDNS_CONTROL" show timedout-packets`

exit 0
