#!/bin/sh
#
#  pdns_auth_packetcache munin plugin.
#  Written by Florus Both <florus@yeetta.net> 2013-05-17
#  Placed in the public domain
#
#  Requires running as root:
#
#    echo '[pdns_auth_*]' > /usr/local/etc/munin/plugin-conf.d/pdns_auth
#    echo 'user root' >> /usr/local/etc/munin/plugin-conf.d/pdns_auth
#
#  Configuration variables:
#
#    pdns_control:    Path to rec_control executable
#                     (default: /usr/local/bin/pdns_control)

PDNS_CONTROL="${pdns_control:-/usr/local/bin/pdns_control}"

if [ "$1" = "autoconf" ]; then
	if [ -e "$PDNS_CONTROL" ]; then
		echo yes
		exit 0
	else
		echo no
		exit 1
	fi
fi

if [ "$1" = "config" ]; then
	echo 'graph_title PowerDNS Auth Packet Cache'
	echo 'graph_order pchit pcmiss pcsize'
	echo 'graph_vlabel queries'
	echo 'graph_info Packet cache'
	echo 'graph_category PowerDNS'

	echo 'pchit.label Packet Cache Hits'
	echo 'pchit.min 0'
	echo 'pchit.max 1000000'
	echo 'pchit.type DERIVE'
	echo 'pchit.info Packet Cache Hits'

	echo 'pcmiss.label Packet Cache Misses'
	echo 'pcmiss.min 0'
	echo 'pcmiss.max 1000000'
	echo 'pcmiss.type DERIVE'
	echo 'pcmiss.info Packet Cache Misses'

	echo 'pcsize.label Packet Cache Size'
	echo 'pcsize.min 0'
	echo 'pcsize.max 1000000'
	echo 'pcsize.type DERIVE'
	echo 'pcsize.info Packet Cache Size'

	exit 0
fi

echo pchit.value `"$PDNS_CONTROL" show packetcache-hit`
echo pcmiss.value `"$PDNS_CONTROL" show packetcache-miss`
echo pcsize.value `"$PDNS_CONTROL" show packetcache-size`

exit 0
